name: PreviousNextDrupal CS
on: [push]
jobs:
  code-style:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['8.0', '8.1', '8.2']
    steps:
      - uses: actions/checkout@v2
      - uses: "shivammathur/setup-php@v2"
        with:
          php-version: ${{ matrix.php-versions }}
        env:
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: "Install dependencies"
        uses: "ramsey/composer-install@v2"
      - name: "Run PHPCS"
        run: |
          ./bin/phpcs

  static-analysis:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['8.0', '8.1', '8.2']
    steps:
      - uses: actions/checkout@v2
      - uses: "shivammathur/setup-php@v2"
        with:
          php-version: ${{ matrix.php-versions }}
        env:
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: "Install dependencies"
        uses: "ramsey/composer-install@v2"
      - name: "Run PHPStan"
        run: |
          ./bin/phpstan analyse --no-progress

  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['8.0', '8.1', '8.2']
        dependency-versions: ['highest', 'lowest']
    steps:
      - uses: actions/checkout@v2
      - uses: "shivammathur/setup-php@v2"
        with:
          php-version: ${{ matrix.php-versions }}
        env:
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup problem matchers for PHP
        run: echo "::add-matcher::${{ runner.tool_cache }}/php.json"
      - name: Setup problem matchers for PHPUnit
        run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"
      - name: "Install dependencies"
        uses: "ramsey/composer-install@v2"
        with:
          dependency-versions: ${{ matrix.dependency-versions }}
      - name: "Run tests"
        run: |
          ./bin/phpunit
